# Slicing Rows & Columns with loc()

##  ----  Quick Summary ----
## What are major import topics features?
### 1. iloc[0], first
### 2. iloc[1], second, iloc[-1] last
### 3. iloc[[0,1,2]] or iloc[0:3]
### 4. iloc[:5] first 5 row
### 5. iloc[-5:] last 5 row

In [1]:
import pandas as pd

In [2]:
summer = pd.read_csv("summer.csv")

In [3]:
summer.head(5)

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver

In [4]:
summer = pd.read_csv("summer.csv",index_col="Athlete")

In [5]:
summer.head(5)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

## loc["PHELPS, Michael"] directly finds the swimmer

In [6]:
summer.loc["PHELPS, Michael"]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Butterfly,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Freestyle,Bronze
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Individual Medley,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,400M Individual Medley,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X100M Freestyle Relay,Bronze
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X100M Medley Relay,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X200M Freestyle Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Butterfly,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Freestyle,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Individual Medley,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,400M Individual Medley,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X100M Freestyle Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X100M Medley Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X200M Freestyle Relay,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,200M Butterfly,Silver
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,200M Medley,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X100M Freestyle,Silver
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X100M Medley,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X200M Freestyle,Gold

## loc["PHELPS, Michael","Medal"] directly finds the medals of Phelps

In [10]:
summer.loc["PHELPS, Michael","Medal"]

Athlete
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael    Bronze
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael    Bronze
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael    Silver
PHELPS, Michael      Gold
PHELPS, Michael    Silver
PHELPS, Michael      Gold
PHELPS, Michael      Gold
Name: Medal, dtype: object

## loc["PHELPS, Michael","Medal","Event"] ERROR

In [12]:
summer.loc["PHELPS, Michael","Medal","Event"]

IndexingError: Too many indexers

## loc["PHELPS, Michael", ["Medal","Event"] ] CORRECT

In [13]:
summer.loc["PHELPS, Michael",["Medal","Event"]]

                  Medal                   Event
Athlete
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael  Bronze          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael  Bronze  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael    Gold          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael    Gold  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael  Silver          200M Butterfly
PHELPS, Michael    Gold             200M Medley
PHELPS, Michael  Silver        4X100M Freestyle
PHELPS, Michael    Gold           4X100M Medley
PHELPS, Michael    Gold        4X200M Freestyle

## loc[ [ "PHELPS, Michael", "LEWIS, Carl" ] ["Medal","Event"] ] 2 swimmer + 2 feature

In [15]:
summer.loc[["PHELPS, Michael","LEWIS, Carl"],["Medal","Event"]]

                  Medal                   Event
Athlete
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael  Bronze          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael  Bronze  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael    Gold          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael    Gold  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael  Silver          200M Butterfly
PHELPS, Michael    Gold             200M Medley
PHELPS, Michael  Silver        4X100M Freestyle
PHELPS, Michael    Gold           4X100M Medley
PHELPS, Michael    Gold        4X200M Freestyle
LEWIS, Carl        Gold                    100M
LEWIS, Carl        Gold                    200M
LEWIS, Carl        Gold            4X100M Relay
LEWIS, Carl        Gold               Long Jump
LEWIS, Carl        Gold                    100M
LEWIS, Carl      Silver                    200M
LEWIS, Carl        Gold               Long Jump
LEWIS, Carl        Gold            4X100M Relay
LEWIS, Carl        Gold               Long Jump
LEWIS, Carl        Gold               Long Jump

## loc[ : , ["Medal","Event"] ]  All rows of Medal and Event

In [16]:
summer.loc[:,["Medal","Event"]]

                            Medal                       Event
Athlete
HAJOS, Alfred                Gold              100M Freestyle
HERSCHMANN, Otto           Silver              100M Freestyle
DRIVAS, Dimitrios          Bronze  100M Freestyle For Sailors
MALOKINIS, Ioannis           Gold  100M Freestyle For Sailors
CHASAPIS, Spiridon         Silver  100M Freestyle For Sailors
...                           ...                         ...
JANIKOWSKI, Damian         Bronze                    Wg 84 KG
REZAEI, Ghasem Gholamreza    Gold                    Wg 96 KG
TOTROV, Rustam             Silver                    Wg 96 KG
ALEKSANYAN, Artur          Bronze                    Wg 96 KG
LIDBERG, Jimmy             Bronze                    Wg 96 KG

[31165 rows x 2 columns]

In [20]:
print("--"*500)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [17]:
summer.head(10)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold

## loc[: "CHASAPIS, Spiridon" ]  All rows  including "CHASAPIS, Spiridon"

In [19]:
summer.loc[:"CHASAPIS, Spiridon"]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

If we try with Phelps, ther is a duplicate entry for him so that it gives an error

In [21]:
print("--"*500)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [22]:
summer.head(20)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver

## loc[ "DRIVAS, Dimitrios" : "BLAKE, Arthur" ] from "DRIVAS, Dimitrios" to "BLAKE, Arthur"

In [25]:
summer.loc["DRIVAS, Dimitrios":"BLAKE, Arthur"]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver

## from "City" to "Discipline"

In [27]:
summer.loc["DRIVAS, Dimitrios":"BLAKE, Arthur" , "City":"Discipline"]

                         City      Sport Discipline
Athlete
DRIVAS, Dimitrios      Athens   Aquatics   Swimming
MALOKINIS, Ioannis     Athens   Aquatics   Swimming
CHASAPIS, Spiridon     Athens   Aquatics   Swimming
CHOROPHAS, Efstathios  Athens   Aquatics   Swimming
HAJOS, Alfred          Athens   Aquatics   Swimming
ANDREOU, Joannis       Athens   Aquatics   Swimming
CHOROPHAS, Efstathios  Athens   Aquatics   Swimming
NEUMANN, Paul          Athens   Aquatics   Swimming
PEPANOS, Antonios      Athens   Aquatics   Swimming
LANE, Francis          Athens  Athletics  Athletics
SZOKOLYI, Alajos       Athens  Athletics  Athletics
BURKE, Thomas          Athens  Athletics  Athletics
HOFMANN, Fritz         Athens  Athletics  Athletics
CURTIS, Thomas         Athens  Athletics  Athletics
GOULDING, Grantley     Athens  Athletics  Athletics
LERMUSIAUX, Albin      Athens  Athletics  Athletics
FLACK, Edwin           Athens  Athletics  Athletics
BLAKE, Arthur          Athens  Athletics  Athletics